const quotes = [
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "If it works, don't touch it. – Unknown",
  "Stay hungry, stay foolish. – Steve Jobs",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "If it works, don't touch it. – Unknown",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "It always seems impossible until it's done. – Nelson Mandela",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Stay hungry, stay foolish. – Steve Jobs",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Make it work, make it right, make it fast. – Kent Beck",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Make it work, make it right, make it fast. – Kent Beck",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Action is the foundational key to all success. – Pablo Picasso",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "If it works, don't touch it. – Unknown",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Fix the cause, not the symptom. – Steve Maguire",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Stay hungry, stay foolish. – Steve Jobs",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Make it work, make it right, make it fast. – Kent Beck",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "If it works, don't touch it. – Unknown",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Action is the foundational key to all success. – Pablo Picasso",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "It always seems impossible until it's done. – Nelson Mandela",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "If it works, don't touch it. – Unknown",
  "If it works, don't touch it. – Unknown",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Make it work, make it right, make it fast. – Kent Beck",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "The secret of getting ahead is getting started. – Mark Twain",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Fix the cause, not the symptom. – Steve Maguire",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "If it works, don't touch it. – Unknown",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Make it work, make it right, make it fast. – Kent Beck",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "It always seems impossible until it's done. – Nelson Mandela",
  "It always seems impossible until it's done. – Nelson Mandela",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "First, solve the problem. Then, write the code. – John Johnson",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Action is the foundational key to all success. – Pablo Picasso",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Make it work, make it right, make it fast. – Kent Beck",
  "First, solve the problem. Then, write the code. – John Johnson",
  "Make it work, make it right, make it fast. – Kent Beck",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "First, solve the problem. Then, write the code. – John Johnson",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Action is the foundational key to all success. – Pablo Picasso",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Fix the cause, not the symptom. – Steve Maguire",
  "Stay hungry, stay foolish. – Steve Jobs",
  "If it works, don't touch it. – Unknown",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. – Martin Fowler",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "If it works, don't touch it. – Unknown",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The secret of getting ahead is getting started. – Mark Twain",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "If it works, don't touch it. – Unknown",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "It always seems impossible until it's done. – Nelson Mandela",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "In order to be irreplaceable, one must always be different. – Coco Chanel",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Stay hungry, stay foolish. – Steve Jobs",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Action is the foundational key to all success. – Pablo Picasso",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "If it works, don't touch it. – Unknown",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "If it works, don't touch it. – Unknown",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "If it works, don't touch it. – Unknown",
  "If it works, don't touch it. – Unknown",
  "A goal without a plan is just a wish. – Antoine de Saint-Exupéry",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "If it works, don't touch it. – Unknown",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Before software can be reusable it first has to be usable. – Ralph Johnson",
  "Action is the foundational key to all success. – Pablo Picasso",
  "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Don’t comment bad code—rewrite it. – Brian Kernighan",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Simplicity is the soul of efficiency. – Austin Freeman",
  "Talk is cheap. Show me the code. – Linus Torvalds",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "The way to get started is to quit talking and begin doing. – Walt Disney",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "Believe you can and you're halfway there. – Theodore Roosevelt",
  "Make it work, make it right, make it fast. – Kent Beck",
  "Code is like humor. When you have to explain it, it’s bad. – Cory House",
  "The best error message is the one that never shows up. – Thomas Fuchs",
  "If it works, don't touch it. – Unknown",
  "The earlier you start to code, the better you become at thinking. – Unknown",
  "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
  "It always seems impossible until it's done. – Nelson Mandela",
  "The only way to learn a new programming language is by writing programs in it. – Dennis Ritchie",
  "If it works, don't touch it. – Unknown",
  "It always seems impossible until it's done. – Nelson Mandela",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair"
];